language: go

go:
  - "1.14"

branches:
  only:
    - master
    - staging
    - develop

jobs:
  include:
    - stage: CI
      name: "Package & build"    
      script:
        - echo "Hello World"
        - go build .
    - name: "Run vet"
      script:
        - go vet .
    - name: "Run Linting"
      install:
        - go get -u golang.org/x/lint/golint
      script:
        - golint .
    - name: "Unit Tests"
      script:
        - cd test && go test -v

    - stage: Deploy
      if: branch = master
      name: "Dummy deploy stage"
      script:
        - echo "Deploy"

notifications:
  slack: ${{ secrets.SLACK_TRAVIS_CHANNEL }}:${{ secrets.SLACK_TRAVIS_TOKEN }}